version: '3.8'

services:
    postgres:
        image: postgres:12.5-alpine
        container_name: time_allocation_project_postgres
        restart: always
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_DB=db_time_allocation_project
          - POSTGRES_PASSWORD=postgres_password
     